apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo
  labels:
    app: react-demo
    role: frontend
spec:
  template:
    metadata:
      labels:
        app: react-demo
        role: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: react-ui
        image: hailongitzero/react:v2
        ports:
          - containerPort: 80
        env:
        - name: BASE_URL
          value: api
  selector:
    matchLabels:
      app: react-demo
      role: frontend
  replicas: 2
