apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels: 
    role: frontend
spec:
  selector:
    app: react-demo
    role: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
