apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels: 
    role: frontend
spec:
  selector:
    app: react-demo
    role: frontend
  type: LoadBalancer
  externalIPs:
    - 10.64.43.109
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
